modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/pouffy/Create-More-Sandpapers/issues"
[[mods]]
modId="createsandpapers"
version="${file.jarVersion}"
displayName="Create: More Sand Papers"
updateJSONURL="https://raw.githubusercontent.com/pouffy/Create-More-Sandpapers/refs/heads/versions/forge_versions.json"
displayURL="https://modrinth.com/mod/create-more-sandpapers"
logoFile="logo.gif"
credits=""
authors="DrMangoTea- Code, Duke Pepa- Textures, PouffyDev- Maintainer"
description='''
Adds sandpapers from modded sands.
'''
[[dependencies.createsandpapers]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createsandpapers]]
    modId="create"
    mandatory=true
    versionRange="[6.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createsandpapers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
