modLoader="javafml"
# The loader version doesn't matter. Modify the Forge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
issueTrackerURL="https://github.com/pouffy/Create-More-Sandpapers/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/create-more-sandpapers"
logoFile="logo.gif"
authors="${mod_author}"
description='''${mod_description}'''

# No mixins needed
# [[mixins]]
# config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${ mod_id }]]
modId = "create"
type = "required"
versionRange = "[6.0.2,)"
ordering = "NONE"
side = "BOTH"